### ISSUE TITLE
Is it relvant for VS 2017 ?

### ISSUE THREAD

**Issue by Eldadc** [mbikovitsky/trustme#1]
Hi,

Is it relevant for Microsoft Visual Studio Installer Projects vsix for VS 2017 ?

Thanks

**Comment by mbikovitsky** [comment]
If you're referring to an offline installation of Visual Studio 2017 - then no, this is not relevant. The VS2017 offline installer comes with the necessary certificates bundled in (in the `certificates` folder). Just install those before launching the main installer, and it should work.

In fact, judging by the answers to my [original post](https://stackoverflow.com/questions/32590194/visual-studio-2015-enterprise-offline-installation-fails), it seems that at some point Microsoft fixed the issue for VS2015 as well.

**Comment by Eldadc** [comment]
Hi,

Thanks for your reply.
I was referring to Microsoft Visual Studio Installer Projects vsix , Is it relevant ?
How can I resolve such issue in my offline network?

Thanks

**Comment by mbikovitsky** [comment]
On that matter I'm afraid I cannot help you.
